# ORIGINAL #####################################################################
################################################################################

e ::= "\" ident "." e  # Function abstraction
    | e e              # Function application
    | ident            # Variable use
    | "(" e ")"        # Parentheses

# MASSAGED #####################################################################
################################################################################

e  ::= "\" ident "." e e'
     | ident e'
     | "(" e ")" e'
e' ::= e e'
     | epsilon
